//guardo todas las acciones
//estado y anuncios

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const TAGS_LOADED = 'TAGS_LOADED'
export const TAGS_LOADED_REQUEST = 'TAGS_LOADED_REQUEST'
export const TAGS_LOADED_FAILURE = 'TAGS_LOADED_FAILURE'

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'

export const UI_RESET_ERROR = 'UI_RESET_ERROR'

export const ADS_LOADED = 'ADS_LOADED'
export const ADS_LOADED_FAILURE = 'ADS_LOADED_FAILURE'
export const ADS_LOADED_REQUEST = 'ADS_LOADED_REQUEST'

export const AD_LOADED_SUCCESS = 'AD_LOADED_SUCCESS'
export const AD_LOADED_FAILURE = 'AD_LOADED_FAILURE'
export const AD_LOADED_REQUEST = 'AD_LOADED_REQUEST'

export const AD_CREATED_SUCCESS = 'AD_CREATED_SUCCESS'
export const AD_CREATED_FAILURE = 'AD_CREATED_FAILURE'
export const AD_CREATED_REQUEST = 'AD_CREATED_REQUEST'

export const AD_DELETED_SUCCESS = 'AD_DELETED_SUCCESS'
export const AD_DELETED_FAILURE = 'AD_DELETED_FAILURE'
export const AD_DELETED_REQUEST = 'AD_DELETED_REQUEST'
